const BANK_PROPERTIES = {
    AGREEMENT_NUMBER: "4321",
    RELATIONSHIP_AGENCY_NUMBER: "3201",
    CHECKING_ACCOUNT_NUMBER: "00012458",
    CHARGING_MODE_NUMBER: "08"
}

const BASE_DATE = new Date(1997, 9, 7)

export var Bank     = BANK_PROPERTIES
export var BaseDate = BASE_DATE